CREATE
OR REPLACE TRIGGER TR_LOG_WIN_AFTER_INSERT
AFTER INSERT ON LOG_WIN
FOR EACH ROW
BEGIN
    DECLARE VAR_USER_ID UUID DEFAULT (
            SELECT
                LRC.PLAYER_USER_ID
            FROM LOG_RESPONSE_CARD AS LRC
            WHERE LRC.RESPONSE_ID = NEW.RESPONSE_ID
        );

    DECLARE VAR_USER_WIN_COUNT INT DEFAULT (
            SELECT
                COUNT(DISTINCT LRC.ROUND_ID)
            FROM LOG_RESPONSE_CARD AS LRC
                INNER JOIN LOG_WIN AS LW ON LW.RESPONSE_ID = LRC.RESPONSE_ID
            WHERE LRC.PLAYER_USER_ID = VAR_USER_ID
        );

    IF VAR_USER_WIN_COUNT >= 1
    AND NOT EXISTS(
        SELECT
            1
        FROM USER_ACHIEVEMENT
        WHERE USER_ID = VAR_USER_ID
            AND ACHIEVEMENTCODE = 'WIN-ROUND-1'
    ) THEN
        INSERT INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENTCODE)
        VALUES (VAR_USER_ID, 'WIN-ROUND-1');
    END
    IF;

    IF VAR_USER_WIN_COUNT >= 10
    AND NOT EXISTS(
        SELECT
            1
        FROM USER_ACHIEVEMENT
        WHERE USER_ID = VAR_USER_ID
            AND ACHIEVEMENTCODE = 'WIN-ROUND-10'
    ) THEN
        INSERT INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENTCODE)
        VALUES (VAR_USER_ID, 'WIN-ROUND-10');
    END
    IF;

    IF VAR_USER_WIN_COUNT >= 100
    AND NOT EXISTS(
        SELECT
            1
        FROM USER_ACHIEVEMENT
        WHERE USER_ID = VAR_USER_ID
            AND ACHIEVEMENTCODE = 'WIN-ROUND-100'
    ) THEN
        INSERT INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENTCODE)
        VALUES (VAR_USER_ID, 'WIN-ROUND-100');
    END
    IF;

    IF VAR_USER_WIN_COUNT >= 1000
    AND NOT EXISTS(
        SELECT
            1
        FROM USER_ACHIEVEMENT
        WHERE USER_ID = VAR_USER_ID
            AND ACHIEVEMENTCODE = 'WIN-ROUND-1000'
    ) THEN
        INSERT INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENTCODE)
        VALUES (VAR_USER_ID, 'WIN-ROUND-1000');
    END
    IF;
END;