CREATE
OR REPLACE EVENT EVT_ADD_ACHIEVEMENTS ON SCHEDULE EVERY 1 DAY
DO
    BEGIN
        DECLARE VAR_LOOP_DONE BOOLEAN DEFAULT FALSE;
        DECLARE VAR_USER_ID UUID;

        DECLARE VAR_USER_CURSOR CURSOR
        FOR
        SELECT
            ID
        FROM USER;

        DECLARE CONTINUE HANDLER
        FOR NOT FOUND
        SET VAR_LOOP_DONE = TRUE;

        OPEN VAR_USER_CURSOR;

            READ_LOOP: LOOP
            FETCH VAR_USER_CURSOR
            INTO
                VAR_USER_ID;

            IF VAR_LOOP_DONE THEN LEAVE READ_LOOP;
            END
            IF;

            CALL SP_ADD_ACHIEVEMENTS(VAR_USER_ID);
            END LOOP;
        CLOSE VAR_USER_CURSOR;
    END;