CREATE
OR REPLACE PROCEDURE SP_ADD_ACHIEVEMENTS(IN VAR_USER_ID UUID)
BEGIN
    DECLARE VAR_USER_WIN_GAME_COUNT INT DEFAULT (
            SELECT
                COUNT(DISTINCT LOBBY_ID)
            FROM V_GAME_WINNER
            WHERE USER_ID = VAR_USER_ID
        );

    DECLARE VAR_USER_WIN_ROUND_COUNT INT DEFAULT (
            SELECT
                COUNT(DISTINCT ROUND_ID)
            FROM V_ROUND_WINNER
            WHERE USER_ID = VAR_USER_ID
        );

    DECLARE VAR_USER_GAMBLE_COUNT INT DEFAULT (
            SELECT
                COUNT(*)
            FROM LOG_CREDITS_SPENT
            WHERE USER_ID = VAR_USER_ID
                AND CATEGORY = 'GAMBLE'
        );

    DECLARE VAR_USER_BET_COUNT INT DEFAULT (
            SELECT
                COUNT(*)
            FROM LOG_CREDITS_SPENT
            WHERE USER_ID = VAR_USER_ID
                AND CATEGORY = 'BET'
        );

    DECLARE VAR_USER_KICK_COUNT INT DEFAULT (
            SELECT
                COUNT(*)
            FROM LOG_KICK
            WHERE USER_ID = VAR_USER_ID
        );

    IF VAR_USER_WIN_GAME_COUNT >= 1 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'WIN-GAME-1');
    END
    IF;

    IF VAR_USER_WIN_GAME_COUNT >= 10 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'WIN-GAME-10');
    END
    IF;

    IF VAR_USER_WIN_GAME_COUNT >= 100 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'WIN-GAME-100');
    END
    IF;

    IF VAR_USER_WIN_ROUND_COUNT >= 10 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'WIN-ROUND-10');
    END
    IF;

    IF VAR_USER_WIN_ROUND_COUNT >= 100 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'WIN-ROUND-100');
    END
    IF;

    IF VAR_USER_WIN_ROUND_COUNT >= 1000 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'WIN-ROUND-1000');
    END
    IF;

    IF VAR_USER_GAMBLE_COUNT >= 1 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'GAMBLE-1');
    END
    IF;

    IF VAR_USER_GAMBLE_COUNT >= 10 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'GAMBLE-10');
    END
    IF;

    IF VAR_USER_GAMBLE_COUNT >= 100 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'GAMBLE-100');
    END
    IF;

    IF VAR_USER_BET_COUNT >= 1 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'BET-1');
    END
    IF;

    IF VAR_USER_BET_COUNT >= 10 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'BET-10');
    END
    IF;

    IF VAR_USER_BET_COUNT >= 100 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'BET-100');
    END
    IF;

    IF VAR_USER_KICK_COUNT >= 1 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'KICK-1');
    END
    IF;

    IF VAR_USER_KICK_COUNT >= 10 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'KICK-10');
    END
    IF;

    IF VAR_USER_KICK_COUNT >= 100 THEN
        INSERT IGNORE INTO USER_ACHIEVEMENT(USER_ID, ACHIEVEMENT_CODE)
        VALUES (VAR_USER_ID, 'KICK-100');
    END
    IF;
END;