CREATE
OR REPLACE PROCEDURE SP_ADD_EXTRA_RESPONSE_UNDO(IN VAR_PLAYER_ID UUID)
BEGIN
    UPDATE PLAYER
    SET EXTRA_RESPONSES = EXTRA_RESPONSES - 1
    WHERE ID = VAR_PLAYER_ID;

    CALL SP_SPEND_CREDITS_UNDO(VAR_PLAYER_ID, 2, 'EXTRA-RESPONSE');
    CALL SP_SET_RESPONSES_PLAYER(VAR_PLAYER_ID);
END;