CREATE
OR REPLACE PROCEDURE SP_GAMBLE_CREDITS(IN VAR_PLAYER_ID UUID, IN VAR_AMOUNT INT)
BEGIN
    DECLARE VAR_GAMBLE_WON BOOLEAN DEFAULT FALSE;

    DECLARE VAR_GAMBLE_ODDS DOUBLE DEFAULT RAND() +
        (
            SELECT
                GAMBLE_ADVANTAGE_SIZE / 100.0
            FROM PLAYER
            WHERE ID = VAR_PLAYER_ID
        );

    CALL SP_SPEND_CREDITS(VAR_PLAYER_ID, VAR_AMOUNT, 'GAMBLE');

    IF VAR_GAMBLE_ODDS > 0.5 THEN
        SET VAR_GAMBLE_WON = TRUE;

        CALL SP_SPEND_CREDITS(
                VAR_PLAYER_ID,
                (VAR_AMOUNT * 2) * -1,
                'GAMBLE-WIN'
            );
    END
    IF;

    SELECT
        VAR_GAMBLE_WON AS GAMBLE_WON
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;
END;