CREATE
OR REPLACE PROCEDURE SP_GAMBLE_CREDITS(IN VAR_PLAYER_ID UUID, IN VAR_AMOUNT INT)
BEGIN
    DECLARE VAR_GAMBLE_WON BOOLEAN DEFAULT FALSE;
    DECLARE VAR_GAMBLE_PICK DOUBLE DEFAULT RAND();
    DECLARE VAR_GAMBLE_THRESHOLD DOUBLE DEFAULT 0.45;

    IF(SELECT GAMBLE_ADVANTAGE FROM PLAYER WHERE ID = VAR_PLAYER_ID) THEN
        SET VAR_GAMBLE_PICK = VAR_GAMBLE_PICK + 0.10;
    END
    IF;

    CALL SP_SPEND_CREDITS(VAR_PLAYER_ID, VAR_AMOUNT, 'GAMBLE');

    IF VAR_GAMBLE_PICK > VAR_GAMBLE_THRESHOLD THEN
        SET VAR_GAMBLE_WON = TRUE;

        CALL SP_SPEND_CREDITS(
                VAR_PLAYER_ID,
                (VAR_AMOUNT * 2) * -1,
                'GAMBLE-WIN'
            );
    END
    IF;

    SELECT
        VAR_GAMBLE_WON AS GAMBLE_WON
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;
END;