CREATE
OR REPLACE PROCEDURE SP_PERK_LARGER_HAND(IN VAR_PLAYER_ID UUID)
BEGIN
    UPDATE PLAYER
    SET LARGER_HAND_SIZE = LARGER_HAND_SIZE + 2
    WHERE ID = VAR_PLAYER_ID;

    CALL SP_DRAW_HAND(VAR_PLAYER_ID);

    CALL SP_SPEND_CREDITS(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('PERK') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'PERK'
        );
END;