CREATE
OR REPLACE PROCEDURE SP_RESPOND_WITH_FORCE_CARD(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_CARD_WAS_PLAYED BOOLEAN DEFAULT FALSE;
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);
    DECLARE VAR_CARD_ID UUID;

    DECLARE VAR_CARDS_NEEDED INT DEFAULT FN_GET_PLAYER_RESPONSE_COUNT(VAR_PLAYER_ID) *
        FN_GET_LOBBY_JUDGE_BLANK_COUNT(VAR_LOBBY_ID);

    DECLARE VAR_CARDS_PLAYED INT DEFAULT FN_GET_PLAYER_RESPONSE_CARD_COUNT(VAR_PLAYER_ID);

    WHILE VAR_CARDS_PLAYED < VAR_CARDS_NEEDED
    DO
        SELECT
            CARD_ID
        INTO
            VAR_CARD_ID
        FROM HAND
        WHERE PLAYER_ID = VAR_PLAYER_ID
        ORDER BY RAND()
        LIMIT 1;

        CALL SP_RESPOND_WITH_CARD(VAR_PLAYER_ID, VAR_CARD_ID, NULL);
        SET VAR_CARDS_PLAYED = FN_GET_PLAYER_RESPONSE_CARD_COUNT(VAR_PLAYER_ID);
        SET VAR_CARD_WAS_PLAYED = TRUE;
    END
    WHILE;

    SELECT
        VAR_CARD_WAS_PLAYED AS CARD_WAS_PLAYED;
END;