CREATE
OR REPLACE PROCEDURE SP_SKIP_JUDGE(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT (
            SELECT
                LOBBY_ID
            FROM PLAYER
            WHERE ID = VAR_PLAYER_ID
        );

    CALL SP_SPEND_CREDITS(VAR_PLAYER_ID, 5, 'SKIP-JUDGE');
    CALL SP_SET_NEXT_JUDGE_PLAYER(VAR_LOBBY_ID);
    CALL SP_SET_RESPONSES_LOBBY(VAR_LOBBY_ID);
END;