CREATE
OR REPLACE FUNCTION FN_GET_SPECIAL_COST(
    IN VAR_CATEGORY ENUM(
        'SKIP-JUDGE',
        'EXTRA-RESPONSE',
        'BLOCK-RESPONSE',
        'SURPRISE',
        'FIND',
        'WILD'
    )
)
RETURNS INT
BEGIN
    RETURN
    CASE
        WHEN VAR_CATEGORY = 'SKIP-JUDGE' THEN 5
        WHEN VAR_CATEGORY = 'EXTRA-RESPONSE' THEN 2
        WHEN VAR_CATEGORY = 'BLOCK-RESPONSE' THEN 2
        WHEN VAR_CATEGORY = 'SURPRISE' THEN 1
        WHEN VAR_CATEGORY = 'FIND' THEN 2
        WHEN VAR_CATEGORY = 'WILD' THEN 3
    END;
END;