CREATE
OR REPLACE FUNCTION FN_GET_SPECIAL_COST(
    IN VAR_PLAYER_ID UUID,
    IN VAR_CATEGORY ENUM(
        'SKIP-JUDGE',
        'EXTRA-RESPONSE',
        'BLOCK-RESPONSE',
        'SURPRISE',
        'STEAL',
        'FIND',
        'WILD'
    )
)
RETURNS INT
BEGIN
    DECLARE VAR_BASE_COST INT DEFAULT (
            CASE
                WHEN VAR_CATEGORY = 'SKIP-JUDGE' THEN 5
                WHEN VAR_CATEGORY = 'EXTRA-RESPONSE' THEN 2
                WHEN VAR_CATEGORY = 'BLOCK-RESPONSE' THEN 2
                WHEN VAR_CATEGORY = 'SURPRISE' THEN 0
                WHEN VAR_CATEGORY = 'STEAL' THEN 1
                WHEN VAR_CATEGORY = 'FIND' THEN 2
                WHEN VAR_CATEGORY = 'WILD' THEN 3
            END
        );

    DECLARE VAR_PLAYER_COST INT DEFAULT VAR_BASE_COST;
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;

    SELECT
        LOBBY_ID,
        USER_ID
    INTO
        VAR_LOBBY_ID,
        VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    WITH PLAYER_RANK AS (
            SELECT
                LRC.PLAYER_USER_ID,
                RANK() OVER (
                    PARTITION BY LRC.LOBBY_ID
                    ORDER BY COUNT(DISTINCT LRC.ROUND_ID) ASC
                ) AS RANKING
            FROM LOG_RESPONSE_CARD AS LRC
                INNER JOIN LOG_WIN AS LW ON LW.RESPONSE_ID = LRC.RESPONSE_ID
            WHERE LRC.LOBBY_ID = VAR_LOBBY_ID
            GROUP BY LRC.PLAYER_USER_ID,
                LRC.LOBBY_ID
        )
    SELECT
        RANKING * VAR_BASE_COST
    INTO
        VAR_PLAYER_COST
    FROM PLAYER_RANK
    WHERE PLAYER_USER_ID = VAR_PLAYER_USER_ID;

    RETURN VAR_PLAYER_COST;
END;