CREATE
OR REPLACE FUNCTION FN_GET_SPECIAL_COST(
    IN VAR_PLAYER_ID UUID,
    IN VAR_CATEGORY ENUM(
        'SKIP-JUDGE',
        'EXTRA-RESPONSE',
        'BLOCK-RESPONSE',
        'SURPRISE',
        'STEAL',
        'FIND',
        'WILD'
    )
)
RETURNS INT
BEGIN
    DECLARE VAR_BASE_COST INT DEFAULT (
            CASE
                WHEN VAR_CATEGORY = 'SKIP-JUDGE' THEN 5
                WHEN VAR_CATEGORY = 'EXTRA-RESPONSE' THEN 2
                WHEN VAR_CATEGORY = 'BLOCK-RESPONSE' THEN 2
                WHEN VAR_CATEGORY = 'SURPRISE' THEN 0
                WHEN VAR_CATEGORY = 'STEAL' THEN 1
                WHEN VAR_CATEGORY = 'FIND' THEN 2
                WHEN VAR_CATEGORY = 'WILD' THEN 3
            END
        );

    DECLARE VAR_PLAYER_COST INT DEFAULT VAR_BASE_COST;

    DECLARE VAR_LOBBY_ID UUID DEFAULT (
            SELECT
                LOBBY_ID
            FROM PLAYER
            WHERE ID = VAR_PLAYER_ID
        );

    WITH PLAYER_RANK AS (
            SELECT
                P.ID,
                RANK() OVER (ORDER BY COUNT(W.ID) ASC) AS RANKING
            FROM PLAYER AS P
                LEFT JOIN WIN AS W ON W.PLAYER_ID = P.ID
            WHERE P.LOBBY_ID = VAR_LOBBY_ID
            GROUP BY P.ID
        )
    SELECT
        VAR_BASE_COST + RANKING - 1
    INTO
        VAR_PLAYER_COST
    FROM PLAYER_RANK
    WHERE ID = VAR_PLAYER_ID;

    RETURN VAR_PLAYER_COST;
END;