CREATE
OR REPLACE FUNCTION FN_GET_PLAYER_RESPONSE_CARD_COUNT(IN VAR_PLAYER_ID UUID)
RETURNS INT
BEGIN
    RETURN (
        SELECT
            COUNT(*)
        FROM RESPONSE_CARD AS RC
            INNER JOIN RESPONSE AS R ON R.ID = RC.RESPONSE_ID
        WHERE PLAYER_ID = VAR_PLAYER_ID
    );
END;