CREATE
OR REPLACE FUNCTION FN_GET_PLAYER_IS_WINNING(IN VAR_PLAYER_ID UUID)
RETURNS BOOLEAN
BEGIN
    DECLARE VAR_PLAYER_IS_WINNING BOOLEAN DEFAULT FALSE;
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;
    DECLARE VAR_WINNER_COUNT INT;

    SELECT
        LOBBY_ID,
        USER_ID
    INTO
        VAR_LOBBY_ID,
        VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    WITH PLAYER_RANK AS (
            SELECT
                LRC.PLAYER_USER_ID,
                RANK() OVER (
                    PARTITION BY LRC.LOBBY_ID
                    ORDER BY COUNT(DISTINCT LRC.ROUND_ID) DESC
                ) AS RANKING
            FROM LOG_RESPONSE_CARD AS LRC
                INNER JOIN LOG_WIN AS LW ON LW.RESPONSE_ID = LRC.RESPONSE_ID
            WHERE LRC.LOBBY_ID = VAR_LOBBY_ID
            GROUP BY LRC.LOBBY_ID,
                LRC.PLAYER_USER_ID
        ),
        WINNERS AS (SELECT PLAYER_USER_ID FROM PLAYER_RANK WHERE RANKING = 1)
    SELECT
        EXISTS(SELECT 1 FROM WINNERS WHERE PLAYER_USER_ID = VAR_PLAYER_USER_ID),
        (SELECT COUNT(*) FROM WINNERS)
    INTO
        VAR_PLAYER_IS_WINNING,
        VAR_WINNER_COUNT;

    IF VAR_WINNER_COUNT > 1 THEN
        SET VAR_PLAYER_IS_WINNING = FALSE;
    END
    IF;

    RETURN VAR_PLAYER_IS_WINNING;
END;