CREATE PROCEDURE IF NOT EXISTS SP_ADD_EXTRA_RESPONSE(
    IN VAR_PLAYER_ID UUID
)
BEGIN
    UPDATE PLAYER
    SET CREDITS_SPENT   = CREDITS_SPENT + 2,
        EXTRA_RESPONSES = EXTRA_RESPONSES + 1
    WHERE ID = VAR_PLAYER_ID;

    CALL SP_SET_RESPONSES_PLAYER(VAR_PLAYER_ID);
END;