CREATE PROCEDURE IF NOT EXISTS SP_BET_ON_WIN(
    IN VAR_PLAYER_ID UUID
)
BEGIN
    UPDATE PLAYER
    SET CREDITS_SPENT = CREDITS_SPENT + 1,
        BET_ON_WIN    = 1
    WHERE ID = VAR_PLAYER_ID;
END;