CREATE PROCEDURE IF NOT EXISTS SP_GAMBLE_CREDITS(
    IN VAR_PLAYER_ID UUID,
    IN VAR_CREDIT_AMOUNT INT
)
BEGIN
    IF RAND() < ((1 / (VAR_CREDIT_AMOUNT * 2)) * (0.75 + (VAR_CREDIT_AMOUNT * 0.05))) THEN
        UPDATE PLAYER
        SET CREDITS_SPENT = CREDITS_SPENT - VAR_CREDIT_AMOUNT
        WHERE ID = VAR_PLAYER_ID;
    ELSE
        UPDATE PLAYER
        SET CREDITS_SPENT = CREDITS_SPENT + VAR_CREDIT_AMOUNT
        WHERE ID = VAR_PLAYER_ID;
    END IF;
END;