CREATE PROCEDURE IF NOT EXISTS SP_GAMBLE_CREDIT(
    IN VAR_PLAYER_ID UUID
)
BEGIN
    IF RAND() < 0.66 THEN
        UPDATE PLAYER
        SET CREDITS_SPENT = CREDITS_SPENT + 1
        WHERE ID = VAR_PLAYER_ID;
    ELSE
        UPDATE PLAYER
        SET CREDITS_SPENT = CREDITS_SPENT - 1
        WHERE ID = VAR_PLAYER_ID;
    END IF;
END;