CREATE PROCEDURE IF NOT EXISTS SP_PICK_WINNER(
    IN VAR_LOBBY_ID UUID,
    IN VAR_CARD_ID UUID
)
BEGIN
    DECLARE VAR_PLAYER_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;
    DECLARE VAR_JUDGE_USER_ID UUID;
    DECLARE VAR_SPECIAL_CATEGORY ENUM ('STEAL','SURPRISE','WILD');

    SELECT PLAYER_ID,
           SPECIAL_CATEGORY
    INTO
        VAR_PLAYER_ID,
        VAR_SPECIAL_CATEGORY
    FROM BOARD
    WHERE LOBBY_ID = VAR_LOBBY_ID
      AND CARD_ID = VAR_CARD_ID;

    SELECT USER_ID
    INTO VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    SELECT P.USER_ID
    INTO VAR_JUDGE_USER_ID
    FROM LOBBY AS L
             INNER JOIN JUDGE AS J ON J.LOBBY_ID = L.ID
             INNER JOIN PLAYER AS P ON P.ID = J.PLAYER_ID
    WHERE L.ID = VAR_LOBBY_ID;

    INSERT INTO WIN (LOBBY_ID, PLAYER_ID)
    VALUES (VAR_LOBBY_ID, VAR_PLAYER_ID);

    INSERT INTO LOG_WIN (LOBBY_ID, PLAYER_USER_ID, JUDGE_USER_ID, CARD_ID, SPECIAL_CATEGORY)
    VALUES (VAR_LOBBY_ID, VAR_PLAYER_USER_ID, VAR_JUDGE_USER_ID, VAR_CARD_ID, VAR_SPECIAL_CATEGORY);

    -- DELETE ANY WILD CARDS
    DELETE C
    FROM CARD AS C
             LEFT JOIN BOARD AS B ON B.CARD_ID = C.ID
    WHERE C.DECK_ID = '00000000-0000-0000-0000-000000000000'
      AND (B.LOBBY_ID IS NULL OR B.LOBBY_ID = VAR_LOBBY_ID);

    DELETE
    FROM BOARD
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    SELECT U.NAME
    FROM PLAYER AS P
             INNER JOIN USER AS U ON U.ID = P.USER_ID
    WHERE P.ID = VAR_PLAYER_ID;
END;