CREATE PROCEDURE IF NOT EXISTS SP_PLAY_CARD (
    IN VAR_PLAYER_ID UUID,
    IN VAR_CARD_ID UUID,
    IN VAR_SPECIAL_CATEGORY ENUM('STEAL','SURPRISE','WILD')
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;
    DECLARE VAR_JUDGE_USER_ID UUID;

    SELECT
        LOBBY_ID,
        USER_ID
    INTO
        VAR_LOBBY_ID,
        VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    SELECT P.USER_ID
    INTO VAR_JUDGE_USER_ID
    FROM JUDGE AS J
        INNER JOIN PLAYER AS P ON P.ID = J.PLAYER_ID
    WHERE J.LOBBY_ID = VAR_LOBBY_ID;

    INSERT INTO BOARD (LOBBY_ID, PLAYER_ID, CARD_ID, SPECIAL_CATEGORY)
    VALUES (VAR_LOBBY_ID, VAR_PLAYER_ID, VAR_CARD_ID, VAR_SPECIAL_CATEGORY);

    INSERT INTO LOG_PLAY (LOBBY_ID, PLAYER_USER_ID, JUDGE_USER_ID, CARD_ID, SPECIAL_CATEGORY)
    VALUES (VAR_LOBBY_ID, VAR_PLAYER_USER_ID, VAR_JUDGE_USER_ID, VAR_CARD_ID, VAR_SPECIAL_CATEGORY);

    DELETE FROM HAND
    WHERE PLAYER_ID = VAR_PLAYER_ID
        AND CARD_ID = VAR_CARD_ID;
END;