CREATE PROCEDURE IF NOT EXISTS SP_SET_JUDGE(
    IN VAR_LOBBY_ID UUID,
    IN VAR_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_CARD_ID UUID;
    SET VAR_CARD_ID = FN_GET_RANDOM_PROMPT_CARD(VAR_LOBBY_ID);

    IF VAR_CARD_ID IS NULL THEN
        DELETE
        FROM JUDGE
        WHERE LOBBY_ID = VAR_LOBBY_ID;
    ELSE
        INSERT IGNORE INTO JUDGE (LOBBY_ID, PLAYER_ID, CARD_ID)
        VALUES (VAR_LOBBY_ID, VAR_PLAYER_ID, VAR_CARD_ID);

        UPDATE JUDGE
        SET PLAYER_ID = VAR_PLAYER_ID,
            CARD_ID   = VAR_CARD_ID
        WHERE LOBBY_ID = VAR_LOBBY_ID;

        DELETE
        FROM DRAW_PILE
        WHERE CARD_ID = VAR_CARD_ID;

        DELETE B
        FROM BOARD AS B
                 INNER JOIN JUDGE AS J ON J.PLAYER_ID = B.PLAYER_ID
        WHERE B.LOBBY_ID = VAR_LOBBY_ID;
    END IF;
END;