CREATE PROCEDURE IF NOT EXISTS SP_SET_NEXT_JUDGE_CARD(
    IN VAR_LOBBY_ID UUID
)
BEGIN
    DECLARE VAR_NEW_CARD_ID UUID;

    SELECT C.ID
    INTO VAR_NEW_CARD_ID
    FROM DRAW_PILE AS DP
             INNER JOIN CARD AS C ON C.ID = DP.CARD_ID
    WHERE C.CATEGORY = 'PROMPT'
      AND DP.LOBBY_ID = VAR_LOBBY_ID
    ORDER BY RAND()
    LIMIT 1;

    UPDATE JUDGE
    SET CARD_ID = VAR_NEW_CARD_ID
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    DELETE
    FROM DRAW_PILE
    WHERE LOBBY_ID = VAR_LOBBY_ID
      AND CARD_ID = VAR_NEW_CARD_ID;
END;