CREATE PROCEDURE IF NOT EXISTS SP_SET_NEXT_PROMPT(
    IN VAR_LOBBY_ID UUID
)
BEGIN
    DECLARE VAR_NEW_PROMPT_CARD_ID UUID DEFAULT FN_GET_RANDOM_PROMPT_CARD(VAR_LOBBY_ID);

    UPDATE LOBBY
    SET PROMPT_CARD_ID = VAR_NEW_PROMPT_CARD_ID
    WHERE ID = VAR_LOBBY_ID;

    DELETE
    FROM DRAW_PILE
    WHERE CARD_ID = VAR_NEW_PROMPT_CARD_ID;
END;