CREATE PROCEDURE IF NOT EXISTS SP_SKIP_JUDGE(
    IN VAR_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;

    SELECT
        LOBBY_ID
    INTO VAR_LOBBY_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    UPDATE PLAYER
    SET
        CREDITS_SPENT = CREDITS_SPENT + 5
    WHERE ID = VAR_PLAYER_ID;

    INSERT
    INTO LOG_CREDITS_SPENT
        (
            LOBBY_ID,
            USER_ID,
            AMOUNT,
            CATEGORY
        )
    SELECT
        LOBBY_ID,
        USER_ID,
        5,
        'SKIP-JUDGE'
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    CALL SP_SET_NEXT_JUDGE_PLAYER(VAR_LOBBY_ID);
    CALL SP_SET_RESPONSES_LOBBY(VAR_LOBBY_ID);
END;
