CREATE PROCEDURE IF NOT EXISTS SP_START_NEW_ROUND(
    IN VAR_LOBBY_ID UUID
)
BEGIN
    UPDATE LOBBY
    SET ROUND_ID = UUID()
    WHERE ID = VAR_LOBBY_ID;

    CALL SP_SET_NEXT_JUDGE_PLAYER(VAR_LOBBY_ID);
    CALL SP_SET_NEXT_JUDGE_CARD(VAR_LOBBY_ID);

    UPDATE JUDGE
    SET RESPONSE_COUNT = 1
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    -- CLEAR ALL RESPONSES
    DELETE R
    FROM RESPONSE AS R
             INNER JOIN PLAYER AS P ON P.ID = R.PLAYER_ID
    WHERE P.LOBBY_ID = VAR_LOBBY_ID;

    -- CREATE NEW RESPONSES
    INSERT INTO RESPONSE (PLAYER_ID)
    SELECT ID
    FROM PLAYER
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    -- DELETE ANY WILD CARDS
    DELETE C
    FROM CARD AS C
             INNER JOIN RESPONSE_CARD AS RC ON RC.CARD_ID = C.ID
             INNER JOIN RESPONSE AS R ON R.ID = RC.RESPONSE_ID
             INNER JOIN PLAYER AS P ON P.ID = R.PLAYER_ID
    WHERE C.DECK_ID = '00000000-0000-0000-0000-000000000000'
      AND P.LOBBY_ID = VAR_LOBBY_ID;
END;