CREATE PROCEDURE IF NOT EXISTS SP_SET_MISSING_PROMPT(
    IN VAR_LOBBY_ID UUID
)
BEGIN
    IF (SELECT PROMPT_CARD_ID
        FROM LOBBY
        WHERE ID = VAR_LOBBY_ID) IS NULL THEN
        CALL SP_SET_NEXT_PROMPT(VAR_LOBBY_ID);
    END IF;
END;