CREATE PROCEDURE IF NOT EXISTS SP_SET_NEXT_JUDGE_CARD(IN VAR_LOBBY_ID UUID)
BEGIN
    DECLARE VAR_NEW_CARD_ID UUID;
    DECLARE VAR_NEW_CARD_TEXT VARCHAR(510);
    DECLARE VAR_BLANK_COUNT INT;
    SET VAR_NEW_CARD_ID = FN_GET_DRAW_PILE_CARD_ID('PROMPT', VAR_LOBBY_ID);

    SELECT
        TEXT
    INTO
        VAR_NEW_CARD_TEXT
    FROM CARD
    WHERE ID = VAR_NEW_CARD_ID;

    SELECT
        ROUND(
            (
                LENGTH(VAR_NEW_CARD_TEXT) -
                LENGTH(REPLACE(VAR_NEW_CARD_TEXT, '_____', ''))
            ) / LENGTH('_____')
        )
    INTO
        VAR_BLANK_COUNT;

    IF VAR_BLANK_COUNT < 1 THEN
        SET VAR_BLANK_COUNT = 1;
    END
    IF;

    UPDATE JUDGE
    SET CARD_ID = VAR_NEW_CARD_ID,
        BLANK_COUNT = COALESCE(VAR_BLANK_COUNT, 1)
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    DELETE
    FROM DRAW_PILE
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND CARD_ID = VAR_NEW_CARD_ID;
END;