CREATE PROCEDURE IF NOT EXISTS SP_SKIP_PROMPT(
    IN VAR_LOBBY_ID UUID
)
BEGIN
    DECLARE VAR_JUDGE_PLAYER_ID UUID DEFAULT FN_GET_LOBBY_JUDGE_PLAYER_ID(VAR_LOBBY_ID);

    INSERT INTO LOG_SKIP (LOBBY_ID, USER_ID, CARD_ID)
    SELECT P.LOBBY_ID,
           P.USER_ID,
           L.PROMPT_CARD_ID AS CARD_ID
    FROM LOBBY AS L
             INNER JOIN PLAYER AS P ON P.LOBBY_ID = L.ID
    WHERE L.ID = VAR_LOBBY_ID
      AND P.ID = VAR_JUDGE_PLAYER_ID;

    CALL SP_SET_NEXT_PROMPT(VAR_LOBBY_ID);
END;