CREATE PROCEDURE IF NOT EXISTS SP_SET_MISSING_JUDGE(
    IN VAR_LOBBY_ID UUID
)
BEGIN
    DECLARE VAR_PLAYER_ID UUID;

    SELECT P.ID
    INTO VAR_PLAYER_ID
    FROM JUDGE AS J
             INNER JOIN PLAYER AS P ON P.ID = J.PLAYER_ID
    WHERE J.LOBBY_ID = VAR_LOBBY_ID
      AND P.IS_ACTIVE = 1;

    IF VAR_PLAYER_ID IS NULL THEN
        SET VAR_PLAYER_ID = FN_GET_RANDOM_LOBBY_PLAYER(VAR_LOBBY_ID);
        IF VAR_PLAYER_ID IS NOT NULL THEN
            CALL SP_SET_JUDGE(VAR_LOBBY_ID, VAR_PLAYER_ID);
        END IF;
    END IF;
END;