CREATE TABLE IF NOT EXISTS USER_ACHIEVEMENT(
    USER_ID UUID NOT NULL,
    ACHIEVEMENT_CATEGORY ENUM(
        'WIN',
        'PLAY',
        'CREDITS-SPENT',
        'DISCARD',
        'SKIP',
        'KICK',
        'FLIP-TABLE'
    ) NOT NULL,
    CREDITS_SPENT_CATEGORY ENUM(
        'WINNING-STREAK',
        'LOSING-STREAK',
        'SKIP-JUDGE',
        'ALERT',
        'GAMBLE',
        'GAMBLE-WIN',
        'BET',
        'BET-WIN',
        'EXTRA-RESPONSE',
        'BLOCK-RESPONSE',
        'STEAL',
        'SURPRISE',
        'FIND',
        'WILD',
        'PERK',
        ''
    ) NOT NULL,
    ACHIEVED_AMOUNT INT NOT NULL,
    PRIMARY KEY(USER_ID, ACHIEVEMENT_CATEGORY, CREDITS_SPENT_CATEGORY),
    FOREIGN KEY(USER_ID) REFERENCES USER (ID) ON DELETE CASCADE
);