CREATE TABLE IF NOT EXISTS USER_ACHIEVEMENT(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    USER_ID UUID NOT NULL,
    ACHIEVEMENT ENUM(
        'WIN-ROUND-1',
        'WIN-ROUND-10',
        'WIN-ROUND-100',
        'WIN-ROUND-1000'
    ) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USER (ID) ON DELETE CASCADE
);