CREATE TABLE IF NOT EXISTS USER_ACHIEVEMENT(
    USER_ID UUID NOT NULL,
    ACHIEVEMENT_CODE ENUM(
        'KICK-1',
        'KICK-10',
        'KICK-20',
        'WIN-GAME-1',
        'WIN-GAME-10',
        'WIN-GAME-100',
        'WIN-ROUND-1',
        'WIN-ROUND-10',
        'WIN-ROUND-100',
        'WIN-ROUND-1000'
    ) NOT NULL,
    PRIMARY KEY(USER_ID, ACHIEVEMENT_CODE),
    FOREIGN KEY(USER_ID) REFERENCES USER (ID) ON DELETE CASCADE
);