DROP DATABASE IF EXISTS CARD_JUDGE;

CREATE DATABASE CARD_JUDGE
    CHARACTER SET = 'UTF8MB4'
    COLLATE = 'UTF8MB4_UNICODE_CI';

USE CARD_JUDGE;

CREATE TABLE USER
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    NAME VARCHAR(255) NOT NULL,
    PASSWORD_HASH CHAR(60) NOT NULL,
    COLOR_THEME VARCHAR(255) NULL,
    IS_ADMIN BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (ID),
    CONSTRAINT NAME_UNIQUE UNIQUE (NAME)
);

CREATE TRIGGER TR_USER_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON USER
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

CREATE TABLE DECK
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    NAME VARCHAR(255) NOT NULL,
    PASSWORD_HASH CHAR(60) NULL,

    PRIMARY KEY (ID),
    CONSTRAINT NAME_UNIQUE UNIQUE (NAME)
);

CREATE TRIGGER TR_DECK_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON DECK
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

CREATE TABLE CARD
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    DECK_ID CHAR(36) NOT NULL,
    CATEGORY ENUM('JUDGE','PLAYER') NOT NULL DEFAULT 'JUDGE',
    TEXT VARCHAR(510) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (DECK_ID) REFERENCES DECK (ID) ON DELETE CASCADE,
    CONSTRAINT DECK_TEXT_UNIQUE UNIQUE (DECK_ID, TEXT)
);

CREATE TRIGGER TR_CARD_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON CARD
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

CREATE TABLE LOBBY
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    NAME VARCHAR(255) NOT NULL,
    PASSWORD_HASH CHAR(60) NULL,
    HAND_SIZE INT NOT NULL DEFAULT 8,

    PRIMARY KEY (ID),
    CONSTRAINT NAME_UNIQUE UNIQUE (NAME)
);

CREATE TRIGGER TR_LOBBY_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON LOBBY
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

CREATE TABLE USER_ACCESS_DECK
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    USER_ID CHAR(36) NOT NULL,
    DECK_ID CHAR(36) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (DECK_ID) REFERENCES DECK (ID) ON DELETE CASCADE,
    CONSTRAINT USER_DECK_UNIQUE UNIQUE (USER_ID, DECK_ID)
);

CREATE TRIGGER TR_USER_ACCESS_DECK_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON USER_ACCESS_DECK
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

DELIMITER //
CREATE TRIGGER TR_DECK_AF_UP_REVOKE_ACCESS
AFTER UPDATE ON DECK
FOR EACH ROW
BEGIN
    IF OLD.PASSWORD_HASH <> NEW.PASSWORD_HASH THEN
        DELETE FROM USER_ACCESS_DECK
        WHERE DECK_ID = NEW.ID;
    END IF;
END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_GET_DECK_ACCESS (
    IN VAR_USER_ID UUID
)
BEGIN
    DECLARE VAR_USER_IS_ADMIN BOOLEAN;

    SELECT IS_ADMIN
    INTO VAR_USER_IS_ADMIN
    FROM USER
    WHERE ID = VAR_USER_ID;

    IF VAR_USER_IS_ADMIN = 1 THEN
        SELECT DISTINCT
            D.ID,
            D.NAME
        FROM DECK AS D
        ORDER BY D.NAME ASC;
    ELSE
        SELECT DISTINCT
            D.ID,
            D.NAME
        FROM DECK AS D
            LEFT JOIN USER_ACCESS_DECK AS UAD ON UAD.DECK_ID = D.ID
        WHERE D.PASSWORD_HASH IS NULL
            OR UAD.USER_ID = VAR_USER_ID
        ORDER BY D.NAME ASC;
    END IF;
END;
//
DELIMITER ;

CREATE TABLE USER_ACCESS_LOBBY
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    USER_ID CHAR(36) NOT NULL,
    LOBBY_ID CHAR(36) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (LOBBY_ID) REFERENCES LOBBY (ID) ON DELETE CASCADE,
    CONSTRAINT USER_LOBBY_UNIQUE UNIQUE (USER_ID, LOBBY_ID)
);

CREATE TRIGGER TR_USER_ACCESS_LOBBY_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON USER_ACCESS_LOBBY
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

DELIMITER //
CREATE TRIGGER TR_LOBBY_AF_UP_REVOKE_ACCESS
AFTER UPDATE ON LOBBY
FOR EACH ROW
BEGIN
    IF OLD.PASSWORD_HASH <> NEW.PASSWORD_HASH THEN
        DELETE FROM USER_ACCESS_LOBBY
        WHERE LOBBY_ID = NEW.ID;
    END IF;
END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_GET_LOBBY_ACCESS (
    IN VAR_USER_ID UUID
)
BEGIN
    DECLARE VAR_USER_IS_ADMIN BOOLEAN;

    SELECT IS_ADMIN
    INTO VAR_USER_IS_ADMIN
    FROM USER
    WHERE ID = VAR_USER_ID;

    IF VAR_USER_IS_ADMIN = 1 THEN
        SELECT DISTINCT
            L.ID,
            L.NAME
        FROM LOBBY AS L
        ORDER BY L.NAME ASC;
    ELSE
        SELECT DISTINCT
            L.ID,
            L.NAME
        FROM LOBBY AS L
            LEFT JOIN USER_ACCESS_LOBBY AS UAL ON UAL.LOBBY_ID = L.ID
        WHERE L.PASSWORD_HASH IS NULL
            OR UAL.USER_ID = VAR_USER_ID
        ORDER BY L.NAME ASC;
    END IF;
END;
//
DELIMITER ;

CREATE TABLE DRAW_PILE
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    LOBBY_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (LOBBY_ID) REFERENCES LOBBY (ID) ON DELETE CASCADE,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE CASCADE,
    CONSTRAINT LOBBY_CARD_UNIQUE UNIQUE (LOBBY_ID, CARD_ID)
);

CREATE TRIGGER TR_DRAW_PILE_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON DRAW_PILE
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

CREATE TABLE PLAYER
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    LOBBY_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT 1,

    PRIMARY KEY (ID),
    FOREIGN KEY (LOBBY_ID) REFERENCES LOBBY (ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    CONSTRAINT LOBBY_USER_UNIQUE UNIQUE (LOBBY_ID, USER_ID)
);

CREATE TRIGGER TR_PLAYER_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON PLAYER
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

DELIMITER //
CREATE PROCEDURE SP_SET_PLAYER_ACTIVE (
    IN VAR_PLAYER_ID UUID,
    IN VAR_LOBBY_ID UUID,
    IN VAR_USER_ID UUID
)
BEGIN
    INSERT IGNORE INTO PLAYER (ID, LOBBY_ID, USER_ID)
    VALUES (VAR_PLAYER_ID, VAR_LOBBY_ID, VAR_USER_ID);

    UPDATE PLAYER
    SET IS_ACTIVE = 1
    WHERE ID = VAR_PLAYER_ID;
END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_SET_PLAYER_INACTIVE (
    IN VAR_LOBBY_ID UUID,
    IN VAR_USER_ID UUID
)
BEGIN
    DECLARE VAR_PLAYER_ID UUID;

    SELECT ID
    INTO VAR_PLAYER_ID
    FROM PLAYER
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND USER_ID = VAR_USER_ID;

    UPDATE PLAYER
    SET IS_ACTIVE = 0
    WHERE ID = VAR_PLAYER_ID;

    DELETE FROM BOARD
    WHERE PLAYER_ID = VAR_PLAYER_ID;
END;
//
DELIMITER ;

CREATE TABLE HAND
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    PLAYER_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    IS_LOCKED BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID) ON DELETE CASCADE,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE CASCADE,
    CONSTRAINT PLAYER_CARD_UNIQUE UNIQUE (PLAYER_ID, CARD_ID)
);

CREATE TRIGGER TR_HAND_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON HAND
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

DELIMITER //
CREATE PROCEDURE SP_DRAW_HAND (
    IN VAR_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_LOBBY_HAND_SIZE INT;
    DECLARE VAR_PLAYER_HAND_SIZE INT;
    DECLARE VAR_CARDS_TO_DRAW INT;

    SELECT L.HAND_SIZE
    INTO VAR_LOBBY_HAND_SIZE
    FROM LOBBY AS L
        INNER JOIN PLAYER AS P ON P.LOBBY_ID = L.ID
    WHERE P.ID = VAR_PLAYER_ID;

    SELECT COUNT(CARD_ID)
    INTO VAR_PLAYER_HAND_SIZE
    FROM HAND
    WHERE PLAYER_ID = VAR_PLAYER_ID;

    SET VAR_CARDS_TO_DRAW = VAR_LOBBY_HAND_SIZE - VAR_PLAYER_HAND_SIZE;

    INSERT INTO HAND (
        PLAYER_ID,
        CARD_ID
    )
    SELECT
        P.ID AS PLAYER_ID,
        C.ID AS CARD_ID
    FROM DRAW_PILE AS DP
        INNER JOIN PLAYER AS P ON P.LOBBY_ID = DP.LOBBY_ID
        INNER JOIN CARD AS C ON C.ID = DP.CARD_ID
    WHERE C.CATEGORY = 'PLAYER'
        AND P.ID = VAR_PLAYER_ID
    ORDER BY RAND()
    LIMIT VAR_CARDS_TO_DRAW;

    DELETE DP
    FROM DRAW_PILE AS DP
        INNER JOIN PLAYER AS P ON P.LOBBY_ID = DP.LOBBY_ID
        INNER JOIN HAND AS H ON H.PLAYER_ID = P.ID AND H.CARD_ID = DP.CARD_ID
    WHERE P.ID = VAR_PLAYER_ID;

    INSERT INTO LOG_DRAW (
        PLAYER_USER_ID,
        CARD_ID
    )
    SELECT
        P.USER_ID AS PLAYER_USER_ID,
        H.CARD_ID
    FROM HAND AS H
        INNER JOIN PLAYER AS P ON P.ID = H.PLAYER_ID
    WHERE P.ID = VAR_PLAYER_ID
    ORDER BY H.CREATED_ON_DATE DESC
    LIMIT VAR_CARDS_TO_DRAW;
END;
//
DELIMITER ;

CREATE TRIGGER TR_PLAYER_AF_IN_DRAW_HAND
AFTER INSERT ON PLAYER
FOR EACH ROW
CALL SP_DRAW_HAND (NEW.ID);

CREATE TABLE JUDGE
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    LOBBY_ID CHAR(36) NOT NULL,
    PLAYER_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (LOBBY_ID) REFERENCES LOBBY (ID) ON DELETE CASCADE,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID) ON DELETE CASCADE,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE CASCADE,
    CONSTRAINT LOBBY_UNIQUE UNIQUE (LOBBY_ID),
    CONSTRAINT PLAYER_UNIQUE UNIQUE (PLAYER_ID)
);

CREATE TRIGGER TR_JUDGE_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON JUDGE
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

DELIMITER //
CREATE PROCEDURE SP_GET_RANDOM_JUDGE_PLAYER (
    IN VAR_LOBBY_ID UUID,
    OUT VAR_PLAYER_ID UUID
)
BEGIN
    SELECT ID
    INTO VAR_PLAYER_ID
    FROM PLAYER
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND IS_ACTIVE = 1
    ORDER BY RAND()
    LIMIT 1;
END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_GET_RANDOM_JUDGE_CARD (
    IN VAR_LOBBY_ID UUID,
    OUT VAR_CARD_ID UUID
)
BEGIN
    SELECT C.ID
    INTO VAR_CARD_ID
    FROM DRAW_PILE AS DP
        INNER JOIN CARD AS C ON C.ID = DP.CARD_ID
    WHERE C.CATEGORY = 'JUDGE'
        AND DP.LOBBY_ID = VAR_LOBBY_ID
    ORDER BY RAND()
    LIMIT 1;
END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_SET_JUDGE (
    IN VAR_LOBBY_ID UUID,
    IN VAR_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_CARD_ID UUID;
    CALL SP_GET_RANDOM_JUDGE_CARD (VAR_LOBBY_ID, VAR_CARD_ID);

    INSERT IGNORE INTO JUDGE (LOBBY_ID, PLAYER_ID, CARD_ID)
    VALUES (VAR_LOBBY_ID, VAR_PLAYER_ID, VAR_CARD_ID);

    UPDATE JUDGE
    SET
        PLAYER_ID = VAR_PLAYER_ID,
        CARD_ID = VAR_CARD_ID
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    DELETE DP
    FROM DRAW_PILE AS DP
        INNER JOIN JUDGE AS J ON J.LOBBY_ID = DP.LOBBY_ID AND J.CARD_ID = DP.CARD_ID;

    DELETE B
    FROM BOARD AS B
        INNER JOIN JUDGE AS J ON J.PLAYER_ID = B.PLAYER_ID
    WHERE B.LOBBY_ID = VAR_LOBBY_ID;
END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_SET_MISSING_JUDGE (
    IN VAR_LOBBY_ID UUID
)
BEGIN
    DECLARE VAR_PLAYER_ID UUID;

    SELECT P.ID
    INTO VAR_PLAYER_ID
    FROM JUDGE AS J
        INNER JOIN PLAYER AS P ON P.ID = J.PLAYER_ID
    WHERE J.LOBBY_ID = VAR_LOBBY_ID
        AND P.IS_ACTIVE = 1;

    IF VAR_PLAYER_ID IS NULL THEN
        CALL SP_GET_RANDOM_JUDGE_PLAYER (VAR_LOBBY_ID, VAR_PLAYER_ID);
        IF VAR_PLAYER_ID IS NOT NULL THEN
            CALL SP_SET_JUDGE (VAR_LOBBY_ID, VAR_PLAYER_ID);
        END IF;
    END IF;
END;
//
DELIMITER ;

CREATE TRIGGER TR_PLAYER_AF_IN_SET_MISSING_JUDGE
AFTER INSERT ON PLAYER
FOR EACH ROW
CALL SP_SET_MISSING_JUDGE (NEW.LOBBY_ID);

CREATE TRIGGER TR_PLAYER_AF_UP_SET_MISSING_JUDGE
AFTER UPDATE ON PLAYER
FOR EACH ROW
CALL SP_SET_MISSING_JUDGE (NEW.LOBBY_ID);

CREATE TRIGGER TR_PLAYER_AF_DL_SET_MISSING_JUDGE
AFTER DELETE ON PLAYER
FOR EACH ROW
CALL SP_SET_MISSING_JUDGE (OLD.LOBBY_ID);

DELIMITER //
CREATE PROCEDURE SP_SKIP_JUDGE_CARD (
    IN VAR_LOBBY_ID UUID
)
BEGIN
    INSERT INTO LOG_SKIP (PLAYER_USER_ID, CARD_ID)
    SELECT
        P.USER_ID AS PLAYER_USER_ID,
        J.CARD_ID
    FROM JUDGE AS J
        INNER JOIN PLAYER AS P ON P.ID = J.PLAYER_ID
    WHERE J.LOBBY_ID = VAR_LOBBY_ID;

    UPDATE JUDGE
    SET
        CARD_ID = (
            SELECT C.ID
            FROM DRAW_PILE AS DP
                INNER JOIN CARD AS C ON C.ID = DP.CARD_ID
            WHERE C.CATEGORY = 'JUDGE'
                AND DP.LOBBY_ID = VAR_LOBBY_ID
            ORDER BY RAND()
            LIMIT 1
        )
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    DELETE DP
    FROM DRAW_PILE AS DP
        INNER JOIN JUDGE AS J ON J.LOBBY_ID = DP.LOBBY_ID AND J.CARD_ID = DP.CARD_ID;
END;
//
DELIMITER ;

CREATE TABLE BOARD
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    LOBBY_ID CHAR(36) NOT NULL,
    PLAYER_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    IS_SURPRISE BOOLEAN NOT NULL DEFAULT 0,
    IS_WILD BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (ID),
    FOREIGN KEY (LOBBY_ID) REFERENCES LOBBY (ID) ON DELETE CASCADE,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID) ON DELETE CASCADE,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE CASCADE
);

CREATE TRIGGER TR_BOARD_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON BOARD
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

CREATE TABLE WIN
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    LOBBY_ID CHAR(36) NOT NULL,
    PLAYER_ID CHAR(36) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (LOBBY_ID) REFERENCES LOBBY (ID) ON DELETE CASCADE,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID) ON DELETE CASCADE
);

CREATE TRIGGER TR_WIN_BF_UP_SET_CHANGED_ON_DATE
BEFORE UPDATE ON WIN
FOR EACH ROW
SET NEW.CHANGED_ON_DATE = CURRENT_TIMESTAMP();

CREATE TRIGGER TR_WIN_AF_IN_SET_JUDGE
AFTER INSERT ON WIN
FOR EACH ROW
CALL SP_SET_JUDGE (NEW.LOBBY_ID, NEW.PLAYER_ID);

DELIMITER //
CREATE PROCEDURE SP_PLAY_CARD (
    IN VAR_PLAYER_ID UUID,
    IN VAR_CARD_ID UUID,
    IN VAR_IS_SURPRISE BOOLEAN
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;
    DECLARE VAR_JUDGE_USER_ID UUID;

    SELECT LOBBY_ID
    INTO VAR_LOBBY_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    SELECT USER_ID
    INTO VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    SELECT P.USER_ID
    INTO VAR_JUDGE_USER_ID
    FROM JUDGE AS J
        INNER JOIN PLAYER AS P ON P.ID = J.PLAYER_ID
    WHERE J.LOBBY_ID = VAR_LOBBY_ID;

    INSERT INTO BOARD (LOBBY_ID, PLAYER_ID, CARD_ID, IS_SURPRISE)
    VALUES (VAR_LOBBY_ID, VAR_PLAYER_ID, VAR_CARD_ID, VAR_IS_SURPRISE);

    INSERT INTO LOG_PLAY (PLAYER_USER_ID, JUDGE_USER_ID, CARD_ID, IS_SURPRISE)
    VALUES(VAR_PLAYER_USER_ID, VAR_JUDGE_USER_ID, VAR_CARD_ID, VAR_IS_SURPRISE);

    DELETE FROM HAND
    WHERE PLAYER_ID = VAR_PLAYER_ID
        AND CARD_ID = VAR_CARD_ID;
END;
//
DELIMITER ;


DELIMITER //
CREATE PROCEDURE SP_PLAY_SURPRISE_CARD (
    IN VAR_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_SURPRISE_CARD_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;

    SELECT LOBBY_ID
    INTO VAR_LOBBY_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;
    
	SELECT USER_ID
    INTO VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    SELECT DP.CARD_ID
    INTO VAR_SURPRISE_CARD_ID
    FROM DRAW_PILE DP
    WHERE DP.LOBBY_ID = VAR_LOBBY_ID
    ORDER BY RAND()
    LIMIT 1;
    
	INSERT INTO LOG_DRAW (PLAYER_USER_ID, CARD_ID, IS_SURPRISE)
    VALUES(VAR_PLAYER_USER_ID, VAR_SURPRISE_CARD_ID, 1);

    CALL SP_PLAY_CARD(VAR_PLAYER_ID, VAR_SURPRISE_CARD_ID, 1);

END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_WITHDRAWAL_CARD (
    IN VAR_PLAYER_ID UUID,
    IN VAR_CARD_ID UUID
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;
    DECLARE VAR_JUDGE_USER_ID UUID;

    SELECT LOBBY_ID
    INTO VAR_LOBBY_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    SELECT USER_ID
    INTO VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    SELECT P.USER_ID
    INTO VAR_JUDGE_USER_ID
    FROM JUDGE AS J
        INNER JOIN PLAYER AS P ON P.ID = J.PLAYER_ID
    WHERE J.LOBBY_ID = VAR_LOBBY_ID;

    INSERT INTO HAND (PLAYER_ID, CARD_ID)
    VALUES (VAR_PLAYER_ID, VAR_CARD_ID);

    DELETE FROM LOG_PLAY
    WHERE PLAYER_USER_ID = VAR_PLAYER_USER_ID
        AND JUDGE_USER_ID = VAR_JUDGE_USER_ID
        AND CARD_ID = VAR_CARD_ID;

    DELETE FROM BOARD
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND PLAYER_ID = VAR_PLAYER_ID
        AND CARD_ID = VAR_CARD_ID;
END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_DISCARD_HAND (
    IN VAR_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_PLAYER_USER_ID UUID;

    SELECT USER_ID
    INTO VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    INSERT INTO LOG_DISCARD (PLAYER_USER_ID, CARD_ID)
    SELECT
        VAR_PLAYER_USER_ID AS PLAYER_USER_ID,
        CARD_ID
    FROM HAND
    WHERE PLAYER_ID = VAR_PLAYER_ID
        AND IS_LOCKED = 0;

    DELETE FROM HAND
    WHERE PLAYER_ID = VAR_PLAYER_ID
        AND IS_LOCKED = 0;
END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_DISCARD_CARD (
    IN VAR_PLAYER_ID UUID,
    IN VAR_CARD_ID UUID
)
BEGIN
    DECLARE VAR_PLAYER_USER_ID UUID;

    SELECT USER_ID
    INTO VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    IF EXISTS(
        SELECT ID
        FROM HAND
        WHERE PLAYER_ID = VAR_PLAYER_ID
            AND CARD_ID = VAR_CARD_ID
            AND IS_LOCKED = 0
    ) THEN
        DELETE FROM HAND
        WHERE PLAYER_ID = VAR_PLAYER_ID
            AND CARD_ID = VAR_CARD_ID;

        INSERT INTO LOG_DISCARD (PLAYER_USER_ID, CARD_ID)
        VALUES(VAR_PLAYER_USER_ID, VAR_CARD_ID);
    END IF;
END;
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_PICK_WINNER (
    IN VAR_LOBBY_ID UUID,
    IN VAR_CARD_ID UUID
)
BEGIN
    DECLARE VAR_PLAYER_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;
    DECLARE VAR_JUDGE_USER_ID UUID;
    DECLARE VAR_IS_SURPRISE BOOLEAN;

    SELECT PLAYER_ID
    INTO VAR_PLAYER_ID
    FROM BOARD
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND CARD_ID = VAR_CARD_ID;
        
	SELECT IS_SURPRISE
    INTO VAR_IS_SURPRISE
    FROM BOARD 
	WHERE LOBBY_ID = VAR_LOBBY_ID
		AND CARD_ID = VAR_CARD_ID;

    SELECT USER_ID
    INTO VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    SELECT P.USER_ID
    INTO VAR_JUDGE_USER_ID
    FROM LOBBY AS L
        INNER JOIN JUDGE AS J ON J.LOBBY_ID = L.ID
        INNER JOIN PLAYER AS P ON P.ID = J.PLAYER_ID
    WHERE L.ID = VAR_LOBBY_ID;

    INSERT INTO WIN (LOBBY_ID, PLAYER_ID)
    VALUES (VAR_LOBBY_ID, VAR_PLAYER_ID);
    
    INSERT INTO LOG_WIN (PLAYER_USER_ID, JUDGE_USER_ID, CARD_ID, IS_SURPRISE)
    VALUES(VAR_PLAYER_USER_ID, VAR_JUDGE_USER_ID, VAR_CARD_ID, VAR_IS_SURPRISE);

    DELETE FROM BOARD
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    SELECT U.NAME
    FROM PLAYER AS P
        INNER JOIN USER AS U ON U.ID = P.USER_ID
    WHERE P.ID = VAR_PLAYER_ID;
END;
//
DELIMITER ;

CREATE TABLE LOG_DRAW
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    PLAYER_USER_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    IS_SURPRISE BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (ID),
    FOREIGN KEY (PLAYER_USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE CASCADE
);

CREATE TABLE LOG_DISCARD
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    PLAYER_USER_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (PLAYER_USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE CASCADE
);

CREATE TABLE LOG_SKIP
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    PLAYER_USER_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (PLAYER_USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE CASCADE
);

CREATE TABLE LOG_PLAY
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    PLAYER_USER_ID CHAR(36) NOT NULL,
    JUDGE_USER_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    IS_SURPRISE BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (ID),
    FOREIGN KEY (PLAYER_USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (JUDGE_USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE CASCADE
);

CREATE TABLE LOG_WIN
(
    ID CHAR(36) NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    PLAYER_USER_ID CHAR(36) NOT NULL,
    JUDGE_USER_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    IS_SURPRISE BOOLEAN NOT NULL DEFAULT 0,

    PRIMARY KEY (ID),
    FOREIGN KEY (PLAYER_USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (JUDGE_USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE CASCADE
);
