CREATE TRIGGER IF NOT EXISTS TR_AF_UP_PLAYER_SET_MISSING_JUDGE
    AFTER UPDATE
    ON PLAYER
    FOR EACH ROW
BEGIN
    IF OLD.IS_ACTIVE <> NEW.IS_ACTIVE THEN
        CALL SP_SET_MISSING_JUDGE(NEW.LOBBY_ID);
    END IF;
END;