CREATE TRIGGER IF NOT EXISTS TR_AUDIT_DECK_DELETE
    AFTER DELETE
    ON DECK
    FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_DECK (
        AUDIT_TYPE,
        DECK_ID,
        NAME,
        PASSWORD_HASH,
        IS_PUBLIC_READONLY,
        IS_LOBBY_WILD_DECK
    ) VALUES (
        'DELETE',
        OLD.ID,
        OLD.NAME,
        OLD.PASSWORD_HASH,
        OLD.IS_PUBLIC_READONLY,
        OLD.IS_LOBBY_WILD_DECK
    );
END;
