CREATE TRIGGER IF NOT EXISTS TR_ADD_RESPONSE_AF_UP_PLAYER
    AFTER UPDATE
    ON PLAYER
    FOR EACH ROW
BEGIN
    IF OLD.IS_ACTIVE <> NEW.IS_ACTIVE THEN
        IF NEW.IS_ACTIVE THEN
            INSERT INTO RESPONSE (PLAYER_ID) VALUE (NEW.ID);
        END IF;
    END IF;
END;