CREATE TRIGGER IF NOT EXISTS TR_DECK_AF_UP_REVOKE_ACCESS
AFTER UPDATE ON DECK
FOR EACH ROW
BEGIN
    IF OLD.PASSWORD_HASH <> NEW.PASSWORD_HASH THEN
        DELETE FROM USER_ACCESS_DECK
        WHERE DECK_ID = NEW.ID;
    END IF;
END;