CREATE TRIGGER IF NOT EXISTS TR_PLAYER_AFTER_UPDATE
    AFTER UPDATE
    ON PLAYER
    FOR EACH ROW
BEGIN
    IF OLD.IS_ACTIVE <> NEW.IS_ACTIVE THEN
        CALL SP_DRAW_HAND(NEW.ID);
        CALL SP_SET_MISSING_JUDGE_PLAYER(NEW.LOBBY_ID);
        CALL SP_SET_MISSING_JUDGE_CARD(NEW.LOBBY_ID);
        CALL SP_SET_RESPONSES_PLAYER(NEW.ID);
    END IF;
END;
