CREATE TRIGGER IF NOT EXISTS TR_SET_MISSING_JUDGE_AF_DL_PLAYER
    AFTER DELETE
    ON PLAYER
    FOR EACH ROW
BEGIN
    IF OLD.IS_JUDGE THEN
        CALL SP_SET_MISSING_JUDGE(OLD.LOBBY_ID);
    END IF;
END;