CREATE TRIGGER IF NOT EXISTS TR_SET_MISSING_JUDGE_AF_UP_PLAYER
    AFTER UPDATE
    ON PLAYER
    FOR EACH ROW
BEGIN
    IF OLD.IS_ACTIVE <> NEW.IS_ACTIVE THEN
        IF OLD.IS_JUDGE THEN
            CALL SP_SET_MISSING_JUDGE(NEW.LOBBY_ID);
        END IF;
    END IF;
END;