CREATE TRIGGER IF NOT EXISTS TR_SET_MISSING_JUDGE_PLAYER_AF_UP_PLAYER
    AFTER UPDATE
    ON PLAYER
    FOR EACH ROW
BEGIN
    IF OLD.IS_ACTIVE <> NEW.IS_ACTIVE THEN
        CALL SP_SET_MISSING_JUDGE_PLAYER(NEW.LOBBY_ID);
    END IF;
END;