CREATE TABLE IF NOT EXISTS LOBBY
(
    ID              UUID         NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    NAME            VARCHAR(255) NOT NULL,
    PASSWORD_HASH   CHAR(60)     NULL,

    HAND_SIZE       INT          NOT NULL DEFAULT 8,
    CREDIT_LIMIT    INT          NOT NULL DEFAULT 3,

    ROUND_ID        UUID         NOT NULL DEFAULT UUID(),
    JUDGE_POSITION  INT          NOT NULL DEFAULT 1,
    PROMPT_CARD_ID  UUID         NULL     DEFAULT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (PROMPT_CARD_ID) REFERENCES CARD (ID) ON DELETE SET NULL,
    CONSTRAINT NAME_UNIQUE UNIQUE (NAME)
);