CREATE TABLE IF NOT EXISTS LOG_WIN
(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    PLAYER_USER_ID UUID NULL,
    JUDGE_USER_ID UUID NULL,
    CARD_ID UUID NULL,
    SPECIAL_CATEGORY ENUM('STEAL','SURPRISE','WILD') NULL DEFAULT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (PLAYER_USER_ID) REFERENCES USER (ID) ON DELETE SET NULL,
    FOREIGN KEY (JUDGE_USER_ID) REFERENCES USER (ID) ON DELETE SET NULL,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE SET NULL
);