CREATE TABLE IF NOT EXISTS PLAYER
(
    ID              UUID     NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CHANGED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    LOBBY_ID        UUID     NOT NULL,
    USER_ID         UUID     NOT NULL,
    IS_ACTIVE       BOOLEAN  NOT NULL DEFAULT 1,
    CREDITS_SPENT   INT      NOT NULL DEFAULT 0,
    EXTRA_RESPONSES INT      NOT NULL DEFAULT 0,

    PRIMARY KEY (ID),
    FOREIGN KEY (LOBBY_ID) REFERENCES LOBBY (ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    CONSTRAINT LOBBY_USER_UNIQUE UNIQUE (LOBBY_ID, USER_ID)
);