alerts:
- disabled: true
  rule: DEPLOYMENT_FAILED
- disabled: true
  rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: REPLACE_APP_NAME
    match:
      path:
        prefix: /
maintenance: {}
name: REPLACE_APP_NAME
region: nyc
services:
- dockerfile_path: Dockerfile
  envs:
  - key: CARD_JUDGE_SQL_HOST
    scope: RUN_AND_BUILD_TIME
    value: REPLACE_CARD_JUDGE_SQL_HOST
  - key: CARD_JUDGE_SQL_USER
    scope: RUN_AND_BUILD_TIME
    value: REPLACE_CARD_JUDGE_SQL_USER
  - key: CARD_JUDGE_SQL_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: REPLACE_CARD_JUDGE_SQL_PASSWORD
  - key: CARD_JUDGE_SQL_DATABASE
    scope: RUN_AND_BUILD_TIME
    value: CARD_JUDGE
  - key: CARD_JUDGE_JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: REPLACE_CARD_JUDGE_JWT_SECRET
  github:
    branch: main
    repo: REPLACE_CARD_JUDGE_GIT_REPO
  http_port: 2016
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: REPLACE_APP_NAME
  source_dir: /