CREATE
OR REPLACE VIEW ACHIEVEMENT AS
SELECT
    'WIN-ROUND-1' AS CODE,
    'Win a round' AS NAME
UNION
SELECT
    'WIN-ROUND-10' AS CODE,
    'Win 10 rounds' AS NAME
UNION
SELECT
    'WIN-ROUND-100' AS CODE,
    'Win 100 rounds' AS NAME
UNION
SELECT
    'WIN-ROUND-1000' AS CODE,
    'Win 1000 rounds' AS NAME;