CREATE
OR REPLACE VIEW V_ACHIEVEMENT AS
SELECT
    UA.ACHIEVEMENT_CATEGORY,
    UA.CREDITS_SPENT_CATEGORY,
    UA.ACHIEVEMENT_NAME,
    AA.ACHIEVEMENT_AMOUNT
FROM (
        SELECT DISTINCT
            ACHIEVEMENT_CATEGORY,
            CREDITS_SPENT_CATEGORY,
            ACHIEVEMENT_NAME,
            ACHIEVEMENT_ORDER
        FROM USER_ACHIEVEMENT
    ) AS UA
    CROSS JOIN (SELECT 1 AS ACHIEVEMENT_AMOUNT UNION SELECT 10 UNION SELECT 100) AS AA
ORDER BY UA.ACHIEVEMENT_ORDER,
    AA.ACHIEVEMENT_AMOUNT;