CREATE
OR REPLACE VIEW V_GAME_WINNER AS
SELECT
    LOBBY_ID,
    USER_ID,
    TIMESTAMP
FROM (
        SELECT
            LOBBY_ID,
            USER_ID,
            COUNT(DISTINCT ROUND_ID) AS ROUND_WIN_COUNT,
            RANK() OVER (PARTITION BY LOBBY_ID ORDER BY ROUND_WIN_COUNT DESC) AS RANKING,
            MAX(TIMESTAMP) AS TIMESTAMP
        FROM V_ROUND_WINNER
        GROUP BY LOBBY_ID,
            USER_ID
    ) AS LOBBY_RANKING
WHERE RANKING = 1;