CREATE
OR REPLACE VIEW V_ROUND_WINNER AS
SELECT
    LRC.LOBBY_ID,
    LRC.ROUND_ID,
    LRC.PLAYER_USER_ID AS USER_ID
FROM LOG_RESPONSE_CARD AS LRC
    INNER JOIN LOG_WIN AS LW ON LW.RESPONSE_ID = LRC.RESPONSE_ID;