CREATE FUNCTION IF NOT EXISTS FN_GET_DRAW_PILE_CARD_ID(
    IN VAR_CATEGORY ENUM ('PROMPT','RESPONSE'),
    IN VAR_LOBBY_ID UUID
) RETURNS UUID
BEGIN
    RETURN (
        SELECT
            C.ID
        FROM DRAW_PILE AS DP
            INNER JOIN CARD AS C ON C.ID = DP.CARD_ID
        WHERE C.CATEGORY = VAR_CATEGORY
          AND DP.LOBBY_ID = VAR_LOBBY_ID
        ORDER BY RAND()
        LIMIT 1
    );
END;