CREATE FUNCTION IF NOT EXISTS FN_GET_LOBBY_JUDGE_PLAYER_ID(
    IN VAR_LOBBY_ID UUID
) RETURNS UUID
BEGIN
    return (SELECT ID
            FROM PLAYER
            WHERE LOBBY_ID = VAR_LOBBY_ID
              AND IS_ACTIVE = 1
              AND IS_JUDGE = 1
            LIMIT 1);
END;