CREATE FUNCTION IF NOT EXISTS FN_GET_RANDOM_PROMPT_CARD(
    IN VAR_LOBBY_ID UUID
) RETURNS UUID
BEGIN
    RETURN (SELECT C.ID
            FROM DRAW_PILE AS DP
                     INNER JOIN CARD AS C ON C.ID = DP.CARD_ID
            WHERE C.CATEGORY = 'PROMPT'
              AND DP.LOBBY_ID = VAR_LOBBY_ID
            ORDER BY RAND()
            LIMIT 1);
END;