name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        working-directory: ./src
        run: go build -o card-judge

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: card-judge
          path: ./src/card-judge